const data = {
  products: [
    {
      _id: '1',
      name: 'Mueble',
      category: 'mobiliario',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Desconocido',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product, handmade',
    },
    {
      _id: '2',
      name: 'Cama tutifruti',
      category: 'Mascotas',
      image: '/images/p2.jpg',
      price: 100,
      countInStock: 20,
      brand: 'Trueq',
      rating: 4.0,
      numReviews: 10,
      description: 'fabric',
    },
    {
      _id: '3',
      name: 'Dije para perrito',
      category: ']Personalizado',
      image: '/images/p3.jpg',
      price: 220,
      countInStock: 0,
      brand: 'Trueq',
      rating: 4.8,
      numReviews: 17,
      description: 'Laser Cut',
    },
    {
      _id: '4',
      name: 'Percheros',
      category: 'Hogar',
      image: '/images/p4.jpg',
      price: 78,
      countInStock: 15,
      brand: 'Trueq',
      rating: 4.5,
      numReviews: 14,
      description: 'infantiles y personalizados',
    },
    {
      _id: '5',
      name: 'Sillon',
      category: 'mobiliario',
      image: '/images/p5.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Trueq',
      rating: 4.5,
      numReviews: 10,
      description: 'Sillon minimalista 2 plazas',
    },
    {
      _id: '6',
      name: 'Repisas hexagono',
      category: 'Hogar',
      image: '/images/p6.jpg',
      price: 139,
      countInStock: 12,
      brand: 'Trueq',
      rating: 4.5,
      numReviews: 15,
      description: 'Decoración',
    },
  ],
};
export default data;
